# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3bf23a1c4d1d9aa4d6d69263f7187b618ad0456845a2340c846cb6e9f4fa0be8704d8db16a8f0a846bf55ab4dbc928d342b08260426c819c4a20a2015a803fcc

test:
  secret_key_base: 4d28adfca910e53d398d5ee0bd5ee51e14b0515126ff4c5cdc1f1349f64bdffdfd75ce8fe894f593c8169f2446c8c284c9a6bafacface9e6900206d349c48bd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
